src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->ema;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route("/login", name="app_login")
     */
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('app_admin_dashboard');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    /**
     * @Route("/logout", name="app_logout")
     */
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Log in!
{% endblock %}

{% block body %}
  <div class="w-full flex md:items-center md:justify-center h-screen bg-gray-100">
    <div class="flex flex-col md:flex-col w-full max-w-[400px]">
      <div class="login-login text-4xl flex justify-center mb-4">
        Meteo<b class="ml-2">MGMT</b>
      </div>
      <div class="bg-white border border-gray-200 rounded-md text-md">
        <form method="post">
          {% if error %}
            <div class="m-4 bg-red-600 text-white p-2 rounded-md">
              {{ error.messageKey|trans(error.messageData, 'security') }}
            </div>
          {% endif %}

          {# {% if app.user %}
            <div class="mb-3">
              You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_logout') }}">Logout</a>
            </div>
          {% endif %} #}
          <div class="mb-4">
            <div class="mx-4 mt-4">
              <div class="flex items-center border px-2 rounded">
                <i class="fa-solid fa-user"></i>
                <input type="text"
                  id="inputEmail"
                  name="email"
                  class="w-full h-full p-2 ml-2"
                  placeholder="Email"
                  value="{{ last_username }}"
                  autofocus />
              </div>
            </div>
            <div class="mx-4 mt-4">
              <div class="flex items-center border px-2 rounded">
                <i class="fa-solid fa-key"></i>
                <input type="password"
                  id="inputPassword"
                  name="password"
                  class="w-full h-full p-2 ml-2"
                  placeholder="Heslo" />
              </div>
            </div>

            <input type="hidden"
              name="_csrf_token"
              value="{{ csrf_token('authenticate') }}" />
          </div>

          <input type="hidden"
            name="_csrf_token"
            value="{{ csrf_token('authenticate') }}" />

          <div class="btn m-4">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
              type="submit">
              Prihlásiť sa
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}